name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      release:
        description: 'Type `true` to release'
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache Gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-${{ hashFiles('gradle') }}
    - name: Build
      run: ./gradlew assemble
    - name: Release
      if: github.event.inputs.release == 'true'
      env:
        atlassian_private_username: ${{ secrets.ATLASSIAN_PRIVATE_USERNAME }}
      run: |
        echo $atlassian_private_username | base64
